routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::prefix('admin')
    ->namespace('Admin')
    ->group(function(){
        Route::get('/', 'DashboardController@index')
        ->name('dashboard');
        
        Route::Resource('order', 'OrderController');
        Route::Resource('product', 'ProductController');
        Route::Resource('category', 'CategoryController');
        Route::Resource('user', 'UserController');
        
    });

//for example
    // Route::post('/siswa/create','SiswaController@create');
    // Route::get('/siswa/{id}/edit','SiswaController@edit');
    // Route::post('/siswa/{id}/update','SiswaController@update');
    // Route::get('/siswa/{id}/delete','SiswaController@delete');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{

    use SoftDeletes;

    protected $fillable = [
        'category_id','product_name', 'image', 'price', 'stock', 'description'
    ];

    public function category(){
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
    
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;
use App\Category;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(){
        $this->middleware('auth')->except(['create','store','show','edit','update','destroy']);
    }
    
    public function index()
    {
        $products = Product::with('category')->get();
        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();      
        return view('admin.product.create', compact('category'));
    } 

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'category_id' => 'required',
            'product_name' => 'required',
            'image' => 'required',
            'price' => 'required',
            'stock' => 'required',
            'description' => 'required'
        ]); 
        

        $products = Product::create([
            'category_id' => $request->category_id,
            'product_name' => $request->product_name,
            'image' => $request->image,
            'price' => $request->price,
            'stock' => $request->stock,
            'description' => $request->description
        ]);
        return redirect()->route('product.index')->with('success','Movies created successfully!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.master')

@section('content')

<div class="container-fluid">
        @if(session('success'))
        <div class="alert alert-success" role="alert">
            {{ session('success') }}
        </div>
        @endif

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Product</h1>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="card shadow">
        <div class="card-body">
            <form action="{{route('product.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="product_name">Nama Barang</label>
                    <input type="text" class="form-control" name="product_name" placeholder="Nama Barang" value="{{old('product_name')}}">
                </div>
                <div class="form-gorup">
                    <label for="category_id">Nama Brand</label>
                    <select name="category_id" class="form-control">
                        <option value="category_id">Pilih Nama Brand</option>
                        @foreach ($category as $categori)
                        <option value="{{$categori->id}}">
                            {{$categori->category_name}}
                        </option>                           
                        @endforeach
                    </select>
                    <button type="button" class="btn btn-primary btn-sm mt-1" data-toggle="modal" data-target="#staticBackdrop">
                        Tambah Brand
                    </button>
                </div>
                <br>
                <div class="form-group">
                    <label for="price">Harga</label>
                    <input type="number" class="form-control" name="price" placeholder="Harga" value="{{old('price')}}">
                </div>
                <div class="form-group">
                    <label for="stock">Stok</label>
                    <input type="number" class="form-control" name="stock" placeholder="Stok" value="{{old('stock')}}">
                </div>
                <div class="form-group">
                    <label for="image">Gambar</label>
                    <input type="text" class="form-control" name="image" placeholder="Gambar" value="{{old('image')}}">
                </div>
                <div class="form-group">
                    <label for="description">Deskripsi</label>
                    <textarea name="description" rows="10" class="d-block w-100 form-control">{{old('description')}}</textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-block">
                    Simpan
                </button>
            </form>
        </div>
    </div>

</div>
<!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Tambah Brand</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">
            <form action="{{route('category.store')}}" method="POST">
                @csrf
                <div>
                    <label for="category_name">Nama Brand</label>
                    <input type="text" class="form-control" name="category_name" placeholder="Nama Brand" value="{{old('category_name')}}">
                </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Tambah</button>
        </div>
        </form>
        </div>
    </div>
    </div>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container-fluid">
      @if(session('success'))
      <div class="alert alert-success" role="alert">
          {{ session('success') }}
      </div>
      @endif
      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Product</h1>
        <a href="{{route('product.create')}}" class="btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Produk
        </a>
      </div>
        <table class="table table-bordered table-striped table-responsive-sm">
            <thead class="thead-light">
              <tr>
                <th scope="col">No</th>
                <th scope="col">Gambar</th>
                <th scope="col">Name Brand</th>
                <th scope="col">Nama Barang</th>
                <th scope="col">Harga</th>
                <th scope="col">Stok</th>
                <th scope="col">Deskripsi</th>
                <th scope="col">Aksi</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($products as $product)
              <tr>
                <td scope="col">{{$product->id}}</td>
                <td scope="col">{{$product->image}}</td>
                <td scope="col">{{$product->category->category_name}}</td>
                <td scope="col">{{$product->product_name}}</td>
                <td scope="col">{{$product->price}}</td>
                <td scope="col">{{$product->stock}}</td>
                <td scope="col">{{$product->description}}</td>
                <td>
                  <a href="{{route('product.edit', $product->id)}}" class="btn btn-info">
                      <i class="fa fa-pencil-alt"></i>
                  </a>
                  <form action="{{route('product.destroy', $product->id)}}" method="post" class="d-inline">
                      @csrf
                      @method('delete')
                      <button class="btn btn-danger">
                          <i class="fa fa-trash"></i>
                      </button>
                  </form>
                </td>
              </tr>
              @empty
              <tr>
                  <td colspan="7" class="text-center">
                      Data Kosong
                  </td>
              </tr>
              @endforelse
            </tbody>
        </table>
    </div>
        
@endsection